version: "3.8"

volumes:
  StoreroomDb:

networks:
  mysqlNET:
  storeroomNET:

services:
  mysql:
    image: "mysql:5.7"
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - "./scripts/storeroomDbScript.sql:/docker-entrypoint-initdb.d/1.sql"
      - StoreroomDb:/var/lib/mysql
    networks:
      - mysqlNET
    environment:
      - MYSQL_PASSWORD=lalaland 
      - MYSQL_ROOT_PASSWORD=lalaland 
      - MYSQL_ROOT_HOST=%
      - bind-address:0.0.0.0 
  
  storeroom-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: storeroom-api
    networks:
      - mysqlNET
      - storeroomNET
    ports:
      - 5000:2000
    environment:
      - DBHOST=mysql
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://*:2000
      - DOTNET_GENERATE_ASPNET_CERTIFICATE=false
    volumes:
      - $APPDATA\Microsoft\UserSecrets\:/root/.microsoft/usersecrets:ro
      - $USERPROFILE\.aspnet\https:/root/.aspnet/https/
    depends_on:
      - mysql
